//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado(){}
    
        public int id { get; set; }
        public int id_cargo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaEgreso { get; set; }
        public Nullable<System.DateTime> fechaUltModificacion { get; set; }
        public int id_persona { get; set; }
        public string cuit {  get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual persona persona { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
