//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class midasTouchEntities : DbContext
    {
        public midasTouchEntities()
            : base("name=midasTouchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargos { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<compra> compras { get; set; }
        public virtual DbSet<compra_detalle> compra_detalles { get; set; }
        public virtual DbSet<empleado> empleados { get; set; }
        public virtual DbSet<estado> estados { get; set; }
        public virtual DbSet<persona> personas { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<proveedor> proveedors { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipoCliente> tipoClientes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
        public virtual DbSet<venta_detalle> venta_detalles { get; set; }
    }
}
